os: linux

language: python

python:
- 3.5
- 3.6

install:
- pip install -r requirements.txt
- pip install -r requirements-test.txt

script:
- coverage run -m pytest

after_success:
- codecov